# Generated by Django 6.0.1 on 2026-02-01 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
