# Generated by Django 6.0.1 on 2026-02-04 16:00

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0005_task_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
